---
- name: config_packetbeat | configuring packetbeat
  template:
    src: "etc/packetbeat/packetbeat.yml.j2"
    dest: "/etc/packetbeat/packetbeat.yml"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart packetbeat
